AllCops:
  TargetRubyVersion: 2.5.1

  Include:
      - '**/Rakefile'
      - '**/config.ru'

  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - 'config/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/feature_helpers.rb'

# use rails rubocop
Rails:
  Enabled: true

# disable top-level documentation warning
Style/Documentation:
  Enabled: false

# 日本語コメント許可
AsciiComments:
  Enabled: false

# enable definition style like Module::Class
ClassAndModuleChildren:
  Enabled: false

# disable missing magic comment warning
Style/FrozenStringLiteralComment:
  Enabled: false

# disable line is too long warning
Metrics/LineLength:
  Max: 110
  Exclude:
    - 'lib/tasks/**/*'
    - 'lib/**/spec/*'
    - 'spec/**/*'

# dieable Block has too many lines warning
Metrics/BlockLength:
  Max: 15
  Exclude:
    - 'lib/tasks/**/*'
    - 'lib/**/spec/*'
    - 'spec/**/*'

# dieable method has too many lines warning
Metrics/MethodLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'lib/**/spec/*'
    - 'spec/**/*'
